spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: ${LOCAL_DB_DIALECT}

  mail:
    host: ${LOCAL_SMTP_HOST}
    username: ${LOCAL_SMTP_USERNAME}
    password: ${LOCAL_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          port: ${LOCAL_SMTP_PORT}

logging:
  level:
    root: INFO

server:
  port: ${LOCAL_SERVER_PORT}

client-url:
  protocol: http
  domain: localhost
  port: 4200

app-secret: ${LOCAL_APP_SECRET}