spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
